services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://flask_user:flask_pass@db:5432/flask_db
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_default    
      - monitoring
          
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_pass
      POSTGRES_DB: flask_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  app_default:
  monitoring:
    external: true
